name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.2'   # add flutter version or put channel as stable

    - name: Install Dependencies
      run: flutter pub get

    - name: Analyze Code
      run: flutter analyze
    # if we have unit , widget , intergration test then add this run comand also
    # - name: Run Tests
    #   run: flutter test

  build_ios:
    name: Build Flutter (Ios)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.2'   # add flutter version or put channel as stable

    - name: Install Dependencies
      run: flutter pub get

    - name: Clean Project
      run: flutter clean

    - name: Install CocoaPods
      run: |
        cd ios
        pod install
        cd ..

    - name: Build Ios
      run: flutter build ios

  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.2'   # add flutter version or put channel as stable

    - name: Install Dependencies
      run: flutter pub get

    - name: Clean Project
      run: flutter clean

    - name: Build Android
      run: flutter build appbundle
